# Generated by Django 4.0.1 on 2022-01-25 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Telegram user id')),
                ('firstname', models.TextField(verbose_name='First name')),
                ('secondname', models.TextField(verbose_name='Second name')),
                ('username', models.TextField(verbose_name='Username')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.TextField(verbose_name='Ticker')),
                ('name', models.TextField(verbose_name='Name of the security')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bot.user', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolios',
            },
        ),
    ]
